# pake image php
FROM php:8.3


# Install system dependencies
RUN apt-get update -y && apt-get install -y \
    openssl \
    zip \
    unzip \
    git \
    libzip-dev 

# install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql zip


# Set the working directory
WORKDIR /app

COPY . /app/
COPY .env /app/

# Install project dependencies
RUN composer install

# Expose port 
EXPOSE 8001

# start app 
CMD ["php", "artisan", "serve", "--port=8002", "--host=0.0.0.0"]