# pake image php
FROM php:8.3


# Install system dependencies
RUN apt-get update -y && apt-get install -y \
    openssl \
    zip \
    unzip \
    git \
    libzip-dev 

# install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql zip


# Set the working directory
WORKDIR /app/route

COPY . /app/route/
COPY .env /app/route/

# Install project dependencies
RUN composer install

# Expose port 
EXPOSE 8002

# start app 
# Copy startup script
COPY startup.sh /app/driver/startup.sh
RUN chmod +x /app/driver/startup.sh

# start app
CMD ["/app/driver/startup.sh"]